# Generated by Django 5.2.17 on 2026-08-25 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес клиента')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В пути'), ('done', 'Выполнена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Причина отказа доставщика')),
            ],
            options={
                'verbose_name': 'Заявка на доставку',
                'verbose_name_plural': 'Заявки на доставку',
            },
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('items_text', models.TextField(blank=True, default='', verbose_name='Список вещей')),
                ('status', models.CharField(choices=[('awaiting_payment', 'Ожидает оплаты'), ('active', 'Активна'), ('overdue', 'Просрочена'), ('extended_6m', 'Продлена на 6 мес'), ('finished', 'Завершена')], default='awaiting_payment', max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма, ₽')),
                ('traffic_source', models.CharField(blank=True, default='', max_length=100, verbose_name='Метка источника трафика')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouses.box', verbose_name='Бокс')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promotions.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Заказ аренды',
                'verbose_name_plural': 'Заказы аренды',
            },
        ),
    ]
