# Generated by Django 5.2.17 on 2026-08-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rentalorder_overdue_notified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='overdue_notified',
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='last_overdue_notified',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего письма о просрочке'),
        ),
    ]
