# Generated by Django 5.2.17 on 2026-08-25 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='warehouses/', verbose_name='Фото')),
                ('temperature', models.CharField(blank=True, default='', max_length=50, verbose_name='Температура')),
                ('ceiling_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Высота потолков, м')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('contacts', models.CharField(blank=True, default='', max_length=255, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='Этаж')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь, м²')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Длина, м')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ширина, м')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Высота, м')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в месяц, ₽')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('reserved', 'Зарезервирован'), ('occupied', 'Занят')], default='free', max_length=20, verbose_name='Статус')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='warehouses.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
    ]
